### ISSUE TITLE
use the element in jupyter notebook

### ISSUE THREAD

**Issue by priscilluzza** [ginkgobioworks/plotly-plot#2] opened 2016-08-09 07:07 UTC
### Description

It would be nice use the element inside jupyter in the context of the declarative widget:
https://github.com/jupyter-incubator/declarativewidgets#including-a-web-component-in-a-notebook

Apparantly it does not work due to some involvement with requirejs/amd.
An approach that could be applied is  loading plotly with requirejs using a shim. Please refert to https://github.com/jupyter-incubator/declarativewidgets/issues/481 where  you find the description of the issue.
### Expected outcome

Iteractive plot inside the jupyter notebook
### Actual outcome

static image if it is used 

```
<script>
        window.define = undefined
</script>
```

Otherwise the error
Plotly is not defined
### Steps to reproduce

refer to https://github.com/jupyter-incubator/declarativewidgets/issues/481
### Browsers Affected

- [ ] Chrome

not tested with the others

**Comment by myw** [comment] 2016-08-11 02:05
The root cause here is that plotly.js is incompatible with require.js; it is not the element's responsibility to intercede in this situation. Like the core Polymer elements, this element is unopinionated about its surroundings: it's up to the surrounding environment to be configured sanely on its own. I don't intend to tie this element to using require.js (or any other JS module framework) by introducing the shim into this element directly, because other consumers may not have/need/allow it, or the shim might cause other interaction problems.
de Require.JS.

I think in terms of a narrow fix, you should be able to include the shim in your own code somehow. In terms of the broad fix, I don't see a great solution. I agree with the points raised in jupyter-incubator/declarativewidgets#481: widgets should, ideally, be a black box to them. However, when you pick a front-end requirement framework, you force the code you use to be compatible with it: there's no easy way around that problem. It seems to me like the right "long-term" solution, if the goal were to truly use _anything_ inside Jupyter, would be to have whoever is forcing the use of require.js to keep track of imports (not widgets: it's not the widget itself that's the issue) that are incompatible with it and include the shim automatically in those cases. I don't know if that responsibility falls to Jupyter or DeclarativeWidgets, but it's definitely a larger-scope issue than this widget.

Since the `<plotly-plot>` element isn't going to change as a result of this issue, I'm closing it.

**Closed as completed by myw** 2016-08-11 02:05 UTC
