### ISSUE TITLE
Zoom/Pan buttons don't appear over plot.

### ISSUE THREAD

**Issue by cmcneil** [ginkgobioworks/plotly-plot#8] opened 2017-01-17 20:34 UTC
### Description
The hover functions and buttons all appear at the bottom of the page instead of within the plotly graph.

### Expected outcome
Buttons appear on top of Plotly graph.

### Actual outcome
[http://imgur.com/a/yN9wG](http://imgur.com/a/yN9wG)

### Steps to reproduce

Put plotly-plot element inside a view of the polymer starter kit.
Use the example from this repository's Readme.md
 ```
   <div class="card">
          <div class="circle">2</div>
          <h1>View Two</h1>
          <plotly-plot id="waveform" data='[{"x": [1, 2, 3], "y": [4, 11, 23]}]'></plotly-plot>
          <p>Ea duis bonorum nec, falli paulo aliquid ei eum.</p>
    </div>
```
### Browsers Affected

- [ ] Chrome

**Comment by myw** [comment] 2017-01-17 23:20
This is a duplicate of #3

**Closed as completed by myw** 2017-01-17 23:20 UTC
Labels: duplicate

**Comment by cmcneil** [comment] 2017-01-18 00:10
Whoops, my bad. Thanks a lot for the quick response!
